### ISSUE TITLE
openAPI - 학교 식단 호출

### ISSUE THREAD

**Issue by daeundada** [devping-kr/NNplanner-BE#35]
## 1. 개요
- 이 이슈는 openAPI - 학교 식단 API 호출 에 대한 것입니다.

## 2. 요구사항
- [x] 학교기본정보 api 를 먼저 호출
- [ ] 기본 정보값을 토대로 급식식단정보 api 호출
- [ ] 식단 메뉴가 7개 이하인 것들만 db에 저장 하도록 구현
- [ ] food DB에 있는 메뉴로 구성된 식단만 db에 저장 하도록 구현

## Todo
- 병원 식단 api db에 저장
- 
-
