### ISSUE TITLE
openAPI - 병원 메뉴 필터 구현

### ISSUE THREAD

**Issue by daeundada** [devping-kr/NNplanner-BE#38]
## 1. 개요
- 이 이슈는 openAPI - 병원 메뉴 필터 구현에 대한 것입니다.

## 2. 요구사항
- [x] Spring Batch 를 이용한 대용량 데이터 처리
- [x] 병원 메뉴 csv 파일 pgadmin 4 사용하여 Import
- [x] csv 파일로 import한 병원 메뉴 데이터를 필터하여 HospitalMenu DB에 저장

## Todo
- Menu API 구현
- 학교 메뉴 openAPI 호출
