### ISSUE TITLE
menu-categories - 소분류 카테고리

### ISSUE THREAD

**Issue by daeundada** [devping-kr/NNplanner-BE#91]
## 1. 개요
- 이 이슈는 menu-categories - 소분류 카테고리 목록 조회 에 대한 것입니다.

## 2. 요구사항
- [x] major-category 아래 소분류 카테고리 목록을 조회할 수 있는 api 구현
- [x] 중복된 값이 나오지 않도록 쿼리문 작성
- [x] 학교/병원으로 나눠서 구현

## Todo
- 학교,학교명인 경우 추가
- 
-
